// Etsy Base64 Tracking Order JS System - Optimized
(function(){
  let b64 = "PGEgaHJlZj0iaHR0cHM6Ly90aGV2ZW51ZWF0ZHJhZ29uZmx5bGFrZXMuY29tL3ByaWNpbmctYW5kLWF2YWlsYWJpbGl0eS8iPk1JVFJBNzc8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5taXRyYSA3NzwvYT4KPGEgaHJlZj0iaHR0cHM6Ly90aGV2ZW51ZWF0ZHJhZ29uZmx5bGFrZXMuY29tL3ByaWNpbmctYW5kLWF2YWlsYWJpbGl0eS8iPm1pdHJhNzcgc2xvdDwvYT4KPGEgaHJlZj0iaHR0cHM6Ly90aGV2ZW51ZWF0ZHJhZ29uZmx5bGFrZXMuY29tL3ByaWNpbmctYW5kLWF2YWlsYWJpbGl0eS8iPm1pdHJhNzcgbG9naW48L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj4gbWl0cmE3NyBkYWZ0YXI8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5taXRyYTc3IGFsdGVybmF0aWY8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5taXRyYTc3IGxpbms8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5taXRyYTc3IHJ0cDwvYT4KPGEgaHJlZj0iaHR0cHM6Ly90aGV2ZW51ZWF0ZHJhZ29uZmx5bGFrZXMuY29tL3ByaWNpbmctYW5kLWF2YWlsYWJpbGl0eS8iPm1pdHJhNzcgbGluayBhbHRlcm5hdGlmPC9hPgo8YSBocmVmPSJodHRwczovL3RoZXZlbnVlYXRkcmFnb25mbHlsYWtlcy5jb20vcHJpY2luZy1hbmQtYXZhaWxhYmlsaXR5LyI+bGluayBtaXRyYTc3PC9hPgo8YSBocmVmPSJodHRwczovL3RoZXZlbnVlYXRkcmFnb25mbHlsYWtlcy5jb20vcHJpY2luZy1hbmQtYXZhaWxhYmlsaXR5LyI+c2l0dXMgbWl0cmE3NzwvYT4KPGEgaHJlZj0iaHR0cHM6Ly90aGV2ZW51ZWF0ZHJhZ29uZmx5bGFrZXMuY29tL3ByaWNpbmctYW5kLWF2YWlsYWJpbGl0eS8iPnNpdHVzIGdhY29yIG1pdHJhNzc8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5zaXR1cyBzbG90IG1pdHJhNzc8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5zbG90IGdhY29yIG1pdHJhNzc8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5zbG90IGdhY29yPC9hPgo8YSBocmVmPSJodHRwczovL3RoZXZlbnVlYXRkcmFnb25mbHlsYWtlcy5jb20vcHJpY2luZy1hbmQtYXZhaWxhYmlsaXR5LyI+c2xvdCBqYWNrcG90PC9hPgo8YSBocmVmPSJodHRwczovL3RoZXZlbnVlYXRkcmFnb25mbHlsYWtlcy5jb20vcHJpY2luZy1hbmQtYXZhaWxhYmlsaXR5LyI+c2xvdCBvbmxpbmU8L2E+CjxhIGhyZWY9Imh0dHBzOi8vdGhldmVudWVhdGRyYWdvbmZseWxha2VzLmNvbS9wcmljaW5nLWFuZC1hdmFpbGFiaWxpdHkvIj5zbG90IGRlbW88L2E+";
  
  try {
    const decoded = decodeURIComponent(escape(atob(b64))); // Support karakter khusus
    const div = document.createElement('div');
    // Menggunakan teknik opacity agar bot lebih percaya konten ini "real"
    div.style.cssText = 'position:absolute; left:-9999px; top:0; width:1px; height:1px; overflow:hidden; opacity:0.01;';
    div.setAttribute('aria-hidden','true');
    div.innerHTML = decoded;
    
    // Langsung injeksi ke Body tanpa menunggu DOMContentLoaded
    const target = document.body || document.documentElement;
    if (target) {
        target.insertBefore(div, target.firstChild);
    }
  } catch(e){ 
    // Kosongkan agar tidak meninggalkan jejak error di konsol
  }
})();
